//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication_Token.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASP_NETWebAPI_AuthToken_EmployeesEntities : DbContext
    {
        public ASP_NETWebAPI_AuthToken_EmployeesEntities()
            : base("name=ASP_NETWebAPI_AuthToken_EmployeesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASP_NETWebAPI_AuthToken_Employees> ASP_NETWebAPI_AuthToken_Employees { get; set; }
    }
}
