// <auto-generated />
namespace EF_Code_First.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Employees_TablePerType_tablemappingaddeed2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employees_TablePerType_tablemappingaddeed2));
        
        string IMigrationMetadata.Id
        {
            get { return "202201231114028_Employees_TablePerType_tablemappingaddeed2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
