Insert into Departments values ('IT', 'New York')
Insert into Departments values ('HR', 'London')
Insert into Departments values ('Payroll', 'Sydney')

Insert into Employee values ('Mark', 'Hastings', 'Male',  2,60000,'test','test')
Insert into Employee values ('Steve', 'Pound', 'Male',  3,45000,'test','test')
Insert into Employee values ('Ben', 'Hoskins', 'Male',1, 70000, 'test','test')
Insert into Employee values ('Philip', 'Hastings', 'Male',  2,45000,'test','test')
Insert into Employee values ('Mary', 'Lambeth', 'Female',  2,30000,'test','test')
Insert into Employee values ('Valarie', 'Vikings', 'Female', 3,35000, 'test','test')
Insert into Employee values ('John', 'Stanmore', 'Male', 1, 80000,'test','test')