//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EF_DB_First.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Employees_TablePerHierarchy_DBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Employees_TablePerHierarchy_DBContext object using the connection string found in the 'Employees_TablePerHierarchy_DBContext' section of the application configuration file.
        /// </summary>
        public Employees_TablePerHierarchy_DBContext() : base("name=Employees_TablePerHierarchy_DBContext", "Employees_TablePerHierarchy_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Employees_TablePerHierarchy_DBContext object.
        /// </summary>
        public Employees_TablePerHierarchy_DBContext(string connectionString) : base(connectionString, "Employees_TablePerHierarchy_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Employees_TablePerHierarchy_DBContext object.
        /// </summary>
        public Employees_TablePerHierarchy_DBContext(EntityConnection connection) : base(connection, "Employees_TablePerHierarchy_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employees_TablePerHierarchy> Employees_TablePerHierarchy
        {
            get
            {
                if ((_Employees_TablePerHierarchy == null))
                {
                    _Employees_TablePerHierarchy = base.CreateObjectSet<Employees_TablePerHierarchy>("Employees_TablePerHierarchy");
                }
                return _Employees_TablePerHierarchy;
            }
        }
        private ObjectSet<Employees_TablePerHierarchy> _Employees_TablePerHierarchy;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees_TablePerHierarchy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees_TablePerHierarchy(Employees_TablePerHierarchy employees_TablePerHierarchy)
        {
            base.AddObject("Employees_TablePerHierarchy", employees_TablePerHierarchy);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Employees_TablePerHierarchy_Model", Name="ContractEmployees_TablePerHierarchy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContractEmployees_TablePerHierarchy : Employees_TablePerHierarchy
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContractEmployees_TablePerHierarchy object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ContractEmployees_TablePerHierarchy CreateContractEmployees_TablePerHierarchy(global::System.Int32 id)
        {
            ContractEmployees_TablePerHierarchy contractEmployees_TablePerHierarchy = new ContractEmployees_TablePerHierarchy();
            contractEmployees_TablePerHierarchy.ID = id;
            return contractEmployees_TablePerHierarchy;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HourlyPay
        {
            get
            {
                return _HourlyPay;
            }
            set
            {
                OnHourlyPayChanging(value);
                ReportPropertyChanging("HourlyPay");
                _HourlyPay = StructuralObject.SetValidValue(value, "HourlyPay");
                ReportPropertyChanged("HourlyPay");
                OnHourlyPayChanged();
            }
        }
        private Nullable<global::System.Int32> _HourlyPay;
        partial void OnHourlyPayChanging(Nullable<global::System.Int32> value);
        partial void OnHourlyPayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HoursWorked
        {
            get
            {
                return _HoursWorked;
            }
            set
            {
                OnHoursWorkedChanging(value);
                ReportPropertyChanging("HoursWorked");
                _HoursWorked = StructuralObject.SetValidValue(value, "HoursWorked");
                ReportPropertyChanged("HoursWorked");
                OnHoursWorkedChanged();
            }
        }
        private Nullable<global::System.Int32> _HoursWorked;
        partial void OnHoursWorkedChanging(Nullable<global::System.Int32> value);
        partial void OnHoursWorkedChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Employees_TablePerHierarchy_Model", Name="Employees_TablePerHierarchy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(PermanentEmployees_TablePerHierarchy))]
    [KnownTypeAttribute(typeof(ContractEmployees_TablePerHierarchy))]
    public abstract partial class Employees_TablePerHierarchy : EntityObject
    {
        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Employees_TablePerHierarchy_Model", Name="PermanentEmployees_TablePerHierarchy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PermanentEmployees_TablePerHierarchy : Employees_TablePerHierarchy
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PermanentEmployees_TablePerHierarchy object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static PermanentEmployees_TablePerHierarchy CreatePermanentEmployees_TablePerHierarchy(global::System.Int32 id)
        {
            PermanentEmployees_TablePerHierarchy permanentEmployees_TablePerHierarchy = new PermanentEmployees_TablePerHierarchy();
            permanentEmployees_TablePerHierarchy.ID = id;
            return permanentEmployees_TablePerHierarchy;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AnuualSalary
        {
            get
            {
                return _AnuualSalary;
            }
            set
            {
                OnAnuualSalaryChanging(value);
                ReportPropertyChanging("AnuualSalary");
                _AnuualSalary = StructuralObject.SetValidValue(value, "AnuualSalary");
                ReportPropertyChanged("AnuualSalary");
                OnAnuualSalaryChanged();
            }
        }
        private Nullable<global::System.Int32> _AnuualSalary;
        partial void OnAnuualSalaryChanging(Nullable<global::System.Int32> value);
        partial void OnAnuualSalaryChanged();

        #endregion

    }

    #endregion

}
