//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EF_DB_First.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Employees_ConditionalMapping_DBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Employees_ConditionalMapping_DBContext object using the connection string found in the 'Employees_ConditionalMapping_DBContext' section of the application configuration file.
        /// </summary>
        public Employees_ConditionalMapping_DBContext() : base("name=Employees_ConditionalMapping_DBContext", "Employees_ConditionalMapping_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Employees_ConditionalMapping_DBContext object.
        /// </summary>
        public Employees_ConditionalMapping_DBContext(string connectionString) : base(connectionString, "Employees_ConditionalMapping_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Employees_ConditionalMapping_DBContext object.
        /// </summary>
        public Employees_ConditionalMapping_DBContext(EntityConnection connection) : base(connection, "Employees_ConditionalMapping_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmployeesConditionalMapping> EmployeesConditionalMappings
        {
            get
            {
                if ((_EmployeesConditionalMappings == null))
                {
                    _EmployeesConditionalMappings = base.CreateObjectSet<EmployeesConditionalMapping>("EmployeesConditionalMappings");
                }
                return _EmployeesConditionalMappings;
            }
        }
        private ObjectSet<EmployeesConditionalMapping> _EmployeesConditionalMappings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmployeesConditionalMappings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployeesConditionalMappings(EmployeesConditionalMapping employeesConditionalMapping)
        {
            base.AddObject("EmployeesConditionalMappings", employeesConditionalMapping);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Employees_ConditionalMapping_Model", Name="EmployeesConditionalMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmployeesConditionalMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmployeesConditionalMapping object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        public static EmployeesConditionalMapping CreateEmployeesConditionalMapping(global::System.Int32 employeeID)
        {
            EmployeesConditionalMapping employeesConditionalMapping = new EmployeesConditionalMapping();
            employeesConditionalMapping.EmployeeID = employeeID;
            return employeesConditionalMapping;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                if (_EmployeeID != value)
                {
                    OnEmployeeIDChanging(value);
                    ReportPropertyChanging("EmployeeID");
                    _EmployeeID = StructuralObject.SetValidValue(value, "EmployeeID");
                    ReportPropertyChanged("EmployeeID");
                    OnEmployeeIDChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();

        #endregion

    }

    #endregion

}
