//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EF_DB_First.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Employees_TablePerType_DBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Employees_TablePerType_DBContext object using the connection string found in the 'Employees_TablePerType_DBContext' section of the application configuration file.
        /// </summary>
        public Employees_TablePerType_DBContext() : base("name=Employees_TablePerType_DBContext", "Employees_TablePerType_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Employees_TablePerType_DBContext object.
        /// </summary>
        public Employees_TablePerType_DBContext(string connectionString) : base(connectionString, "Employees_TablePerType_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Employees_TablePerType_DBContext object.
        /// </summary>
        public Employees_TablePerType_DBContext(EntityConnection connection) : base(connection, "Employees_TablePerType_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employees_TablePerType> Employees_TablePerType
        {
            get
            {
                if ((_Employees_TablePerType == null))
                {
                    _Employees_TablePerType = base.CreateObjectSet<Employees_TablePerType>("Employees_TablePerType");
                }
                return _Employees_TablePerType;
            }
        }
        private ObjectSet<Employees_TablePerType> _Employees_TablePerType;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees_TablePerType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees_TablePerType(Employees_TablePerType employees_TablePerType)
        {
            base.AddObject("Employees_TablePerType", employees_TablePerType);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Employees_TablePerType_Model", Name="ContractEmployees_TablePerType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContractEmployees_TablePerType : Employees_TablePerType
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContractEmployees_TablePerType object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        public static ContractEmployees_TablePerType CreateContractEmployees_TablePerType(global::System.Int32 employeeID)
        {
            ContractEmployees_TablePerType contractEmployees_TablePerType = new ContractEmployees_TablePerType();
            contractEmployees_TablePerType.EmployeeID = employeeID;
            return contractEmployees_TablePerType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HourlyPay
        {
            get
            {
                return _HourlyPay;
            }
            set
            {
                OnHourlyPayChanging(value);
                ReportPropertyChanging("HourlyPay");
                _HourlyPay = StructuralObject.SetValidValue(value, "HourlyPay");
                ReportPropertyChanged("HourlyPay");
                OnHourlyPayChanged();
            }
        }
        private Nullable<global::System.Int32> _HourlyPay;
        partial void OnHourlyPayChanging(Nullable<global::System.Int32> value);
        partial void OnHourlyPayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HoursWorked
        {
            get
            {
                return _HoursWorked;
            }
            set
            {
                OnHoursWorkedChanging(value);
                ReportPropertyChanging("HoursWorked");
                _HoursWorked = StructuralObject.SetValidValue(value, "HoursWorked");
                ReportPropertyChanged("HoursWorked");
                OnHoursWorkedChanged();
            }
        }
        private Nullable<global::System.Int32> _HoursWorked;
        partial void OnHoursWorkedChanging(Nullable<global::System.Int32> value);
        partial void OnHoursWorkedChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Employees_TablePerType_Model", Name="Employees_TablePerType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(ContractEmployees_TablePerType))]
    [KnownTypeAttribute(typeof(PermanentEmployees_TablePerType))]
    public partial class Employees_TablePerType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employees_TablePerType object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        public static Employees_TablePerType CreateEmployees_TablePerType(global::System.Int32 employeeID)
        {
            Employees_TablePerType employees_TablePerType = new Employees_TablePerType();
            employees_TablePerType.EmployeeID = employeeID;
            return employees_TablePerType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                if (_EmployeeID != value)
                {
                    OnEmployeeIDChanging(value);
                    ReportPropertyChanging("EmployeeID");
                    _EmployeeID = StructuralObject.SetValidValue(value, "EmployeeID");
                    ReportPropertyChanged("EmployeeID");
                    OnEmployeeIDChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Employees_TablePerType_Model", Name="PermanentEmployees_TablePerType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PermanentEmployees_TablePerType : Employees_TablePerType
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PermanentEmployees_TablePerType object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        public static PermanentEmployees_TablePerType CreatePermanentEmployees_TablePerType(global::System.Int32 employeeID)
        {
            PermanentEmployees_TablePerType permanentEmployees_TablePerType = new PermanentEmployees_TablePerType();
            permanentEmployees_TablePerType.EmployeeID = employeeID;
            return permanentEmployees_TablePerType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AnnualSalary
        {
            get
            {
                return _AnnualSalary;
            }
            set
            {
                OnAnnualSalaryChanging(value);
                ReportPropertyChanging("AnnualSalary");
                _AnnualSalary = StructuralObject.SetValidValue(value, "AnnualSalary");
                ReportPropertyChanged("AnnualSalary");
                OnAnnualSalaryChanged();
            }
        }
        private Nullable<global::System.Int32> _AnnualSalary;
        partial void OnAnnualSalaryChanging(Nullable<global::System.Int32> value);
        partial void OnAnnualSalaryChanged();

        #endregion

    }

    #endregion

}
