//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Employees_SelfReferencing_Model", "FK__Employees__Manag__66603565", "Employees_SelfReferencing", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EF_DB_First.Model.Employees_SelfReferencing), "Employees_SelfReferencing1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EF_DB_First.Model.Employees_SelfReferencing), true)]

#endregion

namespace EF_DB_First.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Employees_SelfReferencing_DBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Employees_SelfReferencing_DBContext object using the connection string found in the 'Employees_SelfReferencing_DBContext' section of the application configuration file.
        /// </summary>
        public Employees_SelfReferencing_DBContext() : base("name=Employees_SelfReferencing_DBContext", "Employees_SelfReferencing_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Employees_SelfReferencing_DBContext object.
        /// </summary>
        public Employees_SelfReferencing_DBContext(string connectionString) : base(connectionString, "Employees_SelfReferencing_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Employees_SelfReferencing_DBContext object.
        /// </summary>
        public Employees_SelfReferencing_DBContext(EntityConnection connection) : base(connection, "Employees_SelfReferencing_DBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employees_SelfReferencing> Employees_SelfReferencing
        {
            get
            {
                if ((_Employees_SelfReferencing == null))
                {
                    _Employees_SelfReferencing = base.CreateObjectSet<Employees_SelfReferencing>("Employees_SelfReferencing");
                }
                return _Employees_SelfReferencing;
            }
        }
        private ObjectSet<Employees_SelfReferencing> _Employees_SelfReferencing;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees_SelfReferencing EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees_SelfReferencing(Employees_SelfReferencing employees_SelfReferencing)
        {
            base.AddObject("Employees_SelfReferencing", employees_SelfReferencing);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Employees_SelfReferencing_Model", Name="Employees_SelfReferencing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employees_SelfReferencing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employees_SelfReferencing object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        public static Employees_SelfReferencing CreateEmployees_SelfReferencing(global::System.Int32 employeeID)
        {
            Employees_SelfReferencing employees_SelfReferencing = new Employees_SelfReferencing();
            employees_SelfReferencing.EmployeeID = employeeID;
            return employees_SelfReferencing;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                if (_EmployeeID != value)
                {
                    OnEmployeeIDChanging(value);
                    ReportPropertyChanging("EmployeeID");
                    _EmployeeID = StructuralObject.SetValidValue(value, "EmployeeID");
                    ReportPropertyChanged("EmployeeID");
                    OnEmployeeIDChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeName
        {
            get
            {
                return _EmployeeName;
            }
            set
            {
                OnEmployeeNameChanging(value);
                ReportPropertyChanging("EmployeeName");
                _EmployeeName = StructuralObject.SetValidValue(value, true, "EmployeeName");
                ReportPropertyChanged("EmployeeName");
                OnEmployeeNameChanged();
            }
        }
        private global::System.String _EmployeeName;
        partial void OnEmployeeNameChanging(global::System.String value);
        partial void OnEmployeeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ManagerID
        {
            get
            {
                return _ManagerID;
            }
            set
            {
                OnManagerIDChanging(value);
                ReportPropertyChanging("ManagerID");
                _ManagerID = StructuralObject.SetValidValue(value, "ManagerID");
                ReportPropertyChanged("ManagerID");
                OnManagerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ManagerID;
        partial void OnManagerIDChanging(Nullable<global::System.Int32> value);
        partial void OnManagerIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Employees_SelfReferencing_Model", "FK__Employees__Manag__66603565", "Employees_SelfReferencing1")]
        public EntityCollection<Employees_SelfReferencing> Subordinates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employees_SelfReferencing>("Employees_SelfReferencing_Model.FK__Employees__Manag__66603565", "Employees_SelfReferencing1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employees_SelfReferencing>("Employees_SelfReferencing_Model.FK__Employees__Manag__66603565", "Employees_SelfReferencing1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Employees_SelfReferencing_Model", "FK__Employees__Manag__66603565", "Employees_SelfReferencing")]
        public Employees_SelfReferencing Manager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employees_SelfReferencing>("Employees_SelfReferencing_Model.FK__Employees__Manag__66603565", "Employees_SelfReferencing").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employees_SelfReferencing>("Employees_SelfReferencing_Model.FK__Employees__Manag__66603565", "Employees_SelfReferencing").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employees_SelfReferencing> ManagerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employees_SelfReferencing>("Employees_SelfReferencing_Model.FK__Employees__Manag__66603565", "Employees_SelfReferencing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employees_SelfReferencing>("Employees_SelfReferencing_Model.FK__Employees__Manag__66603565", "Employees_SelfReferencing", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
